DROP TABLE IF EXISTS images;
DROP TABLE IF EXISTS repository;


CREATE TABLE repository (id INTEGER PRIMARY KEY AUTOINCREMENT, rootfs VARCHAR(100));

CREATE TABLE images (id INTEGER PRIMARY KEY AUTOINCREMENT, relpath VARCHAR(50), ddate DATETIME, rootid INTEGER);
