#!/usr/bin/env python
# -*- coding: utf-8 -*-
# Copyright (C) 2009 Marc Poulhiès
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2, or (at your option)
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
#
# Author: Marc Poulhiès


import sys
import os

import tempfile

#mencoder mf://@filelist.ok 
#  -mf w=640:h=480:fps=25:type=jpg 
#  -ovc lavc 
#  -lavcopts vcodec=mpeg4:mbd=2:trell 
#  -oac copy 
#  -o saint-eynard-2008-05-04.avi 

def build_video (file_list, duration, output_filename):
    framerate = int(len(file_list)/duration) # approx framerate
    
    fd,flist = tempfile.mkstemp()
    print fd
    fh = os.fdopen(fd, "w")

    fh.write("\n".join(file_list))
    fh.write("\n")
    fh.close()

    cmd = "mencoder mf://@%s " %flist
    cmdargs =  "-mf w=640:h=480:fps=%d:type=jpg "  %framerate
    cmdargs += "-ovc lavc -lavcopts vcodec=mpeg4:mbd=2:trell -oac copy "

    cmd += cmdargs
    cmd += "-o " + output_filename
    
    print cmd


build_video(["%d.jpg" %x for x in xrange(750)], 20, "output")
 
    
    
